### ISSUE TITLE
line 53 arraysToCombine

### ISSUE THREAD

**Issue by MontyWilliams** [victor-nixora/cryptopunk-nft-generator#5]
So it looks like on line 57 u call an object out of nowhere. **arraysToCombine** Is this a trick repo or something where u dont want to just give away an answer or what? how is it that I can copy your entire code and it dosnt work?

**Comment by victor-nixora** [comment]
in line 53, it's a function register. hence arraysToCombine is a parameter mate. Please have a look at line 40 for where this function getting call. I have tested this code and some others and it worked. So maybe you can do some digging around Javascript functions etc
